version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:7.0
    container_name: inventory_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: inventory_billing
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - inventory_network

  # Backend API service
  api:
    build: .
    container_name: inventory_api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/inventory_billing?authSource=admin
      JWT_SECRET: your_super_secure_jwt_secret_key_for_docker_deployment_at_least_32_chars
      JWT_EXPIRE: 7d
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - inventory_network
    volumes:
      - ./logs:/app/logs

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: inventory_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
    networks:
      - inventory_network

volumes:
  mongodb_data:
    driver: local

networks:
  inventory_network:
    driver: bridge